### ISSUE TITLE
Repo License

### ISSUE THREAD

**Issue by matthew-petrie** [t-kelly/nextjs-shopify-app#2]
Hi, this repo looks fab and I can see you are a developer advocate Shopify. Could you clarify what the licence for this repo is? (and update package file &/or add a LICENCE file?)

Greatly appreciated, Matthew

**Comment by t-kelly** [comment]
Good call @matthew-petrie! Seeing anyone could have made this (not using anything special, exclusive to Shopify employees), I'm putting it under my name.

Added in https://github.com/t-kelly/nextjs-shopify-app/commit/1e61d7acc7ced6545484b35c4f59c4bd9fee8801

**Comment by matthew-petrie** [comment]
Thanks @t-kelly (and for the super fast reply). Looking forward to having a play with it! 😄
